package wanzhi.gulu.community.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import wanzhi.gulu.community.model.Appeal;
import wanzhi.gulu.community.model.AppealExample;

public interface AppealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int countByExample(AppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int deleteByExample(AppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int insert(Appeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int insertSelective(Appeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    List<Appeal> selectByExampleWithRowbounds(AppealExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    List<Appeal> selectByExample(AppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    Appeal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") Appeal record, @Param("example") AppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int updateByExample(@Param("record") Appeal record, @Param("example") AppealExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int updateByPrimaryKeySelective(Appeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appeal
     *
     * @mbggenerated Fri Apr 03 00:29:56 CST 2020
     */
    int updateByPrimaryKey(Appeal record);
}