package wanzhi.gulu.community.model;

public class Appeal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appeal.id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appeal.deal_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    private Long dealId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appeal.question_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appeal.user_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appeal.appeal_reason
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    private String appealReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appeal.gmt_create
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appeal.status
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appeal.id
     *
     * @return the value of appeal.id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appeal.id
     *
     * @param id the value for appeal.id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appeal.deal_id
     *
     * @return the value of appeal.deal_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public Long getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appeal.deal_id
     *
     * @param dealId the value for appeal.deal_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public void setDealId(Long dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appeal.question_id
     *
     * @return the value of appeal.question_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appeal.question_id
     *
     * @param questionId the value for appeal.question_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appeal.user_id
     *
     * @return the value of appeal.user_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appeal.user_id
     *
     * @param userId the value for appeal.user_id
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appeal.appeal_reason
     *
     * @return the value of appeal.appeal_reason
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public String getAppealReason() {
        return appealReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appeal.appeal_reason
     *
     * @param appealReason the value for appeal.appeal_reason
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public void setAppealReason(String appealReason) {
        this.appealReason = appealReason == null ? null : appealReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appeal.gmt_create
     *
     * @return the value of appeal.gmt_create
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appeal.gmt_create
     *
     * @param gmtCreate the value for appeal.gmt_create
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appeal.status
     *
     * @return the value of appeal.status
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appeal.status
     *
     * @param status the value for appeal.status
     *
     * @mbggenerated Tue Mar 31 23:17:03 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}