package wanzhi.gulu.community.model;

public class Like {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.id
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.creator
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.like_id
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    private Long likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.type
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.gmt_create
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.id
     *
     * @return the value of like.id
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.id
     *
     * @param id the value for like.id
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.creator
     *
     * @return the value of like.creator
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.creator
     *
     * @param creator the value for like.creator
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.like_id
     *
     * @return the value of like.like_id
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public Long getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.like_id
     *
     * @param likeId the value for like.like_id
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public void setLikeId(Long likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.type
     *
     * @return the value of like.type
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.type
     *
     * @param type the value for like.type
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.gmt_create
     *
     * @return the value of like.gmt_create
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.gmt_create
     *
     * @param gmtCreate the value for like.gmt_create
     *
     * @mbggenerated Tue Mar 24 21:24:47 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}