package wanzhi.gulu.community.model;

public class Praise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.id
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.creator
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.praise_id
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    private Long praiseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.type
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.gmt_create
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.id
     *
     * @return the value of praise.id
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.id
     *
     * @param id the value for praise.id
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.creator
     *
     * @return the value of praise.creator
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.creator
     *
     * @param creator the value for praise.creator
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.praise_id
     *
     * @return the value of praise.praise_id
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public Long getPraiseId() {
        return praiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.praise_id
     *
     * @param praiseId the value for praise.praise_id
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public void setPraiseId(Long praiseId) {
        this.praiseId = praiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.type
     *
     * @return the value of praise.type
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.type
     *
     * @param type the value for praise.type
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.gmt_create
     *
     * @return the value of praise.gmt_create
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.gmt_create
     *
     * @param gmtCreate the value for praise.gmt_create
     *
     * @mbggenerated Mon Mar 30 22:16:13 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}