package wanzhi.gulu.community.model;

public class ReportDeal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.id
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.target_id
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private Long targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.target_type
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private Integer targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.report_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private Long reportCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.latest_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private Long latestCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.ban_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private Long banCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.status
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.gmt_deal
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private Long gmtDeal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_deal.deal_result
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    private String dealResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.id
     *
     * @return the value of report_deal.id
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.id
     *
     * @param id the value for report_deal.id
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.target_id
     *
     * @return the value of report_deal.target_id
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.target_id
     *
     * @param targetId the value for report_deal.target_id
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.target_type
     *
     * @return the value of report_deal.target_type
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public Integer getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.target_type
     *
     * @param targetType the value for report_deal.target_type
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setTargetType(Integer targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.report_count
     *
     * @return the value of report_deal.report_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public Long getReportCount() {
        return reportCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.report_count
     *
     * @param reportCount the value for report_deal.report_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setReportCount(Long reportCount) {
        this.reportCount = reportCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.latest_count
     *
     * @return the value of report_deal.latest_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public Long getLatestCount() {
        return latestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.latest_count
     *
     * @param latestCount the value for report_deal.latest_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setLatestCount(Long latestCount) {
        this.latestCount = latestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.ban_count
     *
     * @return the value of report_deal.ban_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public Long getBanCount() {
        return banCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.ban_count
     *
     * @param banCount the value for report_deal.ban_count
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setBanCount(Long banCount) {
        this.banCount = banCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.status
     *
     * @return the value of report_deal.status
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.status
     *
     * @param status the value for report_deal.status
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.gmt_deal
     *
     * @return the value of report_deal.gmt_deal
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public Long getGmtDeal() {
        return gmtDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.gmt_deal
     *
     * @param gmtDeal the value for report_deal.gmt_deal
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setGmtDeal(Long gmtDeal) {
        this.gmtDeal = gmtDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_deal.deal_result
     *
     * @return the value of report_deal.deal_result
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public String getDealResult() {
        return dealResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_deal.deal_result
     *
     * @param dealResult the value for report_deal.deal_result
     *
     * @mbggenerated Wed Apr 01 23:10:45 CST 2020
     */
    public void setDealResult(String dealResult) {
        this.dealResult = dealResult == null ? null : dealResult.trim();
    }
}