package wanzhi.gulu.community.model;

public class Star {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.id
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.collector
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    private Long collector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.star_id
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    private Long starId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.gmt_create
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.id
     *
     * @return the value of star.id
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.id
     *
     * @param id the value for star.id
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.collector
     *
     * @return the value of star.collector
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    public Long getCollector() {
        return collector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.collector
     *
     * @param collector the value for star.collector
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    public void setCollector(Long collector) {
        this.collector = collector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.star_id
     *
     * @return the value of star.star_id
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    public Long getStarId() {
        return starId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.star_id
     *
     * @param starId the value for star.star_id
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    public void setStarId(Long starId) {
        this.starId = starId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.gmt_create
     *
     * @return the value of star.gmt_create
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.gmt_create
     *
     * @param gmtCreate the value for star.gmt_create
     *
     * @mbggenerated Tue Mar 31 15:22:09 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}