package wanzhi.gulu.community.model;

public class Tread {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tread.id
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tread.creator
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tread.tread_id
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    private Long treadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tread.type
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tread.gmt_create
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tread.id
     *
     * @return the value of tread.id
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tread.id
     *
     * @param id the value for tread.id
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tread.creator
     *
     * @return the value of tread.creator
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tread.creator
     *
     * @param creator the value for tread.creator
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tread.tread_id
     *
     * @return the value of tread.tread_id
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public Long getTreadId() {
        return treadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tread.tread_id
     *
     * @param treadId the value for tread.tread_id
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public void setTreadId(Long treadId) {
        this.treadId = treadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tread.type
     *
     * @return the value of tread.type
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tread.type
     *
     * @param type the value for tread.type
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tread.gmt_create
     *
     * @return the value of tread.gmt_create
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tread.gmt_create
     *
     * @param gmtCreate the value for tread.gmt_create
     *
     * @mbggenerated Tue Mar 31 22:24:18 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}