package wanzhi.gulu.community.model;

public class Watch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.id
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.collector
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    private Long collector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.watch_id
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    private Long watchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column watch.gmt_create
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.id
     *
     * @return the value of watch.id
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.id
     *
     * @param id the value for watch.id
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.collector
     *
     * @return the value of watch.collector
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    public Long getCollector() {
        return collector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.collector
     *
     * @param collector the value for watch.collector
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    public void setCollector(Long collector) {
        this.collector = collector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.watch_id
     *
     * @return the value of watch.watch_id
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    public Long getWatchId() {
        return watchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.watch_id
     *
     * @param watchId the value for watch.watch_id
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    public void setWatchId(Long watchId) {
        this.watchId = watchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column watch.gmt_create
     *
     * @return the value of watch.gmt_create
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column watch.gmt_create
     *
     * @param gmtCreate the value for watch.gmt_create
     *
     * @mbggenerated Thu Mar 26 00:55:56 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}